name: Workflow CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Fazer checkout do repositório
      uses: actions/checkout@v2
    
    - name: Configurar .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x' # Altere para a versão do .NET que você está usando
    
    - name: Restaurar dependências
      run: dotnet restore

    - name: Verificar estrutura de diretórios
      run: ls -R

    - name: Compilar o projeto
      run: dotnet build --configuration Release --no-restore --verbosity minimal
    
    - name: Executar testes
      run: dotnet test --no-restore --verbosity normal
